### ISSUE TITLE
Issue with search keyword 

### ISSUE THREAD

**Issue by Marwan01** [Marwan01/covid-helpline#21]
**Inaccurate search**
When searching for North Korea, we get results for North Dakota.

**Reproduce**
Text
1. North Korea -> North Dakora
2. South Korea -> South Africa
3. Myanmar -> nothing

**Expected behavior**
Expected to return country more accurately

**Screenshots**
![89983032_816834852138419_7315337918027923456_n](https://user-images.githubusercontent.com/25825598/77130719-08ac4d80-6a27-11ea-991d-1e5d463c149d.jpg)

**Comment by SumiyaChoudhry** [comment]
I think what's happening is that it recognizes the first part of the text (example: North and South) and then picks the first country or state in alphabetical order.

**Comment by SumiyaChoudhry** [comment]
This also happens for United States and or Unites States of America. 

![Image from iOS](https://user-images.githubusercontent.com/62364301/77132119-41025a80-6a2c-11ea-9829-7a540a931a0d.png)

**Comment by AlexAndrei98-LI** [comment]
Mexico -> New Mexico
instead of Mexico

**Comment by jagvirdehal** [comment]
China -> Czechia
