### ISSUE TITLE
Fix text template response/option-menu

### ISSUE THREAD

**Issue by trujivan** [Marwan01/covid-helpline#22]
**Is your feature request related to a problem? Please describe.**

- The messages sent back to users are not in the clearest form. They should be corrected so that the result is clear and concise. 

**Describe the solution you'd like**

- The messages should be blocked effectively: new lines, spaces, along with grammatic splices when appropriate. 

**Describe alternatives you've considered**

**Additional context**

**Comment by SumiyaChoudhry** [comment]
There is also a spelling mistake, it would be nice to get to fixed. 

" Welcome to the Covid-19 Helpline. 
- Text 'Advice' to get **infromation** on how to protect yourself from Covid-19. "

Spelling for information needs to be corrected.
