### ISSUE TITLE
"Information" and "Receive" misspelled 

### ISSUE THREAD

**Issue by glennparham** [Marwan01/covid-helpline#30]
The default message has "Information" and "Receive" misspelled.
Here is where we need to fix this: 
[https://github.com/Marwan01/covid-helpline/blob/master/src/responses.py]( https://github.com/Marwan01/covid-helpline/blob/master/src/responses.py)

<img width="623" alt="Screen Shot 2020-03-23 at 1 00 13 PM" src="https://user-images.githubusercontent.com/19394146/77342220-40a4e080-6d06-11ea-9425-27de7318a01c.png">

**Comment by Marwan01** [comment]
addressed
