### ISSUE TITLE
Make city/state lockdown curfew available via sms

### ISSUE THREAD

**Issue by trujivan** [Marwan01/covid-helpline#46]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Make city/state lockdown curfew available via SMS.

**Describe alternatives you've considered**
Make city/state lockdown curfew available via SMS... may be hardcoded instead of dynamically coded.

**Additional context**
Consider city/states with the most cases.

**Comment by Marwan01** [comment]
no more relevant.
