### ISSUE TITLE
cron schedule for a python 3 function with a requirements txt 

### ISSUE THREAD

**Issue by AlexAndrei98** [Marwan01/covid-helpline#47]
**Cloud function on a cron schedule **
Create a python3 cloud function that reads from google storage and sends texts. Since the datasource updates at 00:00 UTC I figured that we can trigger this at ! UTC
I have attached the code in here https://console.cloud.google.com/functions/list?project=covid-helpline&tab=general. 
**dependencies** 
- Google Storage
- Twillio

**Comment by Marwan01** [comment]
I try

**Comment by Marwan01** [comment]
https://console.cloud.google.com/functions/list?project=covid-helpline&tab=general

**Comment by Marwan01** [comment]
I got it @AlexAndrei98
