### ISSUE TITLE
Slow response time

### ISSUE THREAD

**Issue by SumiyaChoudhry** [Marwan01/covid-helpline#48]
**Describe the bug**
When I reply to with a country/state/city/zipcode, it takes a long time to receive a response. The longest was up to 46 seconds. Happens with all responses. It has been reported by several users. 

**To Reproduce**
Text a City/State or Zipcode

**What the user is looking for.
A faster response time. Replies should be instant.

**Comment by Marwan01** [comment]
resolved.
