### ISSUE TITLE
Keyword Search Fail 2

### ISSUE THREAD

**Issue by SumiyaChoudhry** [Marwan01/covid-helpline#49]
**Describe the bug**
keyword Chicago, send user the Welcome message, I am afraid this might not be the only city that's problematic. Tested for iOS and Android User.

**To Reproduce**
1. Text Chicago

**Expected behavior**
It should show the current data for Chicago

**Screenshots**
![5BE3EF50-AA2B-41CF-ABEB-A6A92BA3FF07](https://user-images.githubusercontent.com/62364301/77839900-c54c9000-7146-11ea-8464-f999fd97cf4c.JPG)
![IMG_6950](https://user-images.githubusercontent.com/62364301/77839902-c8478080-7146-11ea-9629-51ec6ca78c10.jpg)

**Comment by Marwan01** [comment]
@AlexAndrei98 can you look into this? See if we need a if statement or something.

**Comment by Marwan01** [comment]
resolved.
