### ISSUE TITLE
March 28th, 2020 Retro

### ISSUE THREAD

**Issue by SumiyaChoudhry** [Marwan01/covid-helpline#50]
We need a summary of all that we have accomplished collectively, what is working for us and what still needs more work.

**Comment by SumiyaChoudhry** [comment]
Here is a summary of what we have accomplished, what is working, and what we need to work on as of today. 

[COVID19_Helpline Retrospec.docx](https://github.com/Marwan01/covid-helpline/files/4398271/COVID19_Helpline.Retrospec.docx)

**Comment by Marwan01** [comment]
Taking care of automating the share of this document weekly.
